version: 0.0
os: linux
files:
  - source: /deploy/move_init.sh
    destination: /etc/init.d
  - source: /
    destination: /home/ubuntu/emitters-2.1

permissions:
  - object: /etc/init.d/move_init.sh
    owner: root
    mode: 777
    type:
      - file
