version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/emitters-2.1
permissions:
  - object: /home/ubuntu/emitters-2.1/deploy
    pattern: "**"
    owner: ubuntu
    mode: 777
    type:
      - file
hooks:
  AfterInstall:
    - location: /home/ubuntu/emitters-2.1/deploy/move_init.sh
      timeout: 120
      runas: root
